services:
  mongodb:
    image: mongo:latest
    container_name: leadflow_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Auth Service (Go)
  auth-service:
    build: ../auth-service
    container_name: auth_service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGO_URI=mongodb://mongodb:27017/leadflow_auth
      - JWT_SECRET=SecretKey123
    depends_on:
      - mongodb

  # Lead Service (Node.js)
  lead-service:
    build: ../lead-service
    container_name: lead_service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - MONGO_URI=mongodb://mongodb:27017/leadflow_leads
      - JWT_SECRET=SecretKey123
    depends_on:
      - mongodb

  frontend:
    build: ../lead-webservice
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_AUTH_SERVICE_URL=http://localhost:8081
      - NEXT_PUBLIC_LEAD_SERVICE_URL=http://localhost:8082
    depends_on:
      - auth-service
      - lead-service

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - auth-service
      - lead-service
volumes:
  mongo_data: