services:
  # Auth Service (Go)
  auth-service:
    build: ../auth-service
    container_name: ${AUTH_CONTAINER_NAME}
    ports:
      - "${AUTH_PORT}:8081"
    environment:
      - PORT=8081
      - MONGO_URI=${AUTH_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    restart: always

  # Lead Service (Node.js)
  lead-service:
    build: ../lead-service
    container_name: ${LEAD_CONTAINER_NAME}
    ports:
      - "${LEAD_PORT}:8082"
    environment:
      - PORT=8082
      - MONGO_URI=${LEAD_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    restart: always

  frontend:
    build:
      context: ../lead-webservice
      args:
        NEXT_PUBLIC_AUTH_SERVICE_URL: ${NEXT_PUBLIC_AUTH_SERVICE_URL}
        NEXT_PUBLIC_LEAD_SERVICE_URL: ${NEXT_PUBLIC_LEAD_SERVICE_URL}
    container_name: ${FRONTEND_CONTAINER_NAME}
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: always